[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chemlab"
version = "0.1.1"
description = "Utilities for Q-Chem workflows, ML datasets, and scanning"
authors = [
    { name="moriya2524", email="suwako2524@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy"]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
chemlab = "chemlab:__main__:main()"

run_mecp = "chemlab.scripts.run_mecp:main"
export_numpy = "chemlab.scripts.export_numpy:main"
prepare_tddft_inp = "chemlab.scripts.prepare_tddft_inp:main"


